# AWS Redshift Configuration
redshift:
  cluster-id: redshift-cluster-2
  db-name: dev
  region: eu-west-2
  db-user: app_user   # optional
  host: # optional
  port: # optional, defaults to 5439

# Logging Configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.jdbc: INFO